#!/bin/zsh

curDir=$(dirname ${(%):-%x})
cd $curDir

git pull origin master

if [ ! -f $HOME/.oh-my-zsh/oh-my-zsh.sh ]; then
  echo "Oh no! Oh My Zsh is not installed! Please visit https://ohmyz.sh/ for installation instructions."
fi

if [ ! -d $ZSH_CUSTOM/themes/powerlevel10k ]; then
  echo "Snap! Powerlevel10k is not installed! Please follow https://github.com/romkatv/powerlevel10k#oh-my-zsh for installation instructions."
fi

// TODO: solve Read-only file system on macos
function clone_external_plugins() {
  echo "Cloning external plugins..."

  local customPluginthemeDir=$ZSH_CUSTOM/plugins
  local externalPlugins=(
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-syntax-highlighting
  )

  for repo in $externalPlugins; do
    if [ ! -d $customPluginthemeDir/${repo:t} ]; then
      git clone https://github.com/${repo} $customPluginthemeDir/${repo:t}
    fi
  done
}

function init() {
  rsync --include ".zsh*" \
    --include ".zsh/**" \
    --include ".p10k.zsh" \
    --include ".aliases" \
    --include ".gitconfig" \
    --include ".gitignore.txt" \
    --include ".gitmessage.txt" \
    --include ".git_template/" \
    --include ".git_template/**" \
    --include ".vim*" \
    --include ".vim/**" \
    --include ".tmux*" \
    --include ".bin/" \
    --include ".bin/**" \
    --include ".alacritty.yml" \
    --include ".config*" \
    --include ".config/**" \
    --exclude "*" \
    -avh --no-perms . ~
  source ~/.zshrc

  if [ $SHELL != '/bin/zsh' ]; then
    chsh -s $(which zsh) # make zsh your default shell
  fi
}

function configure_asdf() {
  asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  # Needs coreutils package
  asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
}

clone_external_plugins
configure_asdf

if [[ $1 == "--force" ]] || [[ $1 == "-f" ]]; then
  init
else
  # -q for yes/no answers
  if read -q '?This may overwrite existing files in your home directory. Are you sure? (y/n)'; then
    echo ""
    init
  fi
fi

unset init
