#!/bin/zsh

curDir=$(dirname ${(%):-%x})
cd $curDir

git pull origin master

if [ ! -f $HOME/.oh-my-zsh/oh-my-zsh.sh ]; then
  echo "Installing Oh My Zsh..."

  command sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    echo "Installation successful." || \
    echo "The clone has failed."
fi

if [ ! -d $ZSH_CUSTOM/themes/powerlevel10k ]; then
  echo "Installing p10k theme..."

  local themeDir=$ZSH_CUSTOM/themes/powerlevel10k

  command git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $themeDir && \
    echo "Installation successful." || \
    echo "The clone has failed."
fi

// TODO: solve Read-only file system on macos
function clone_external_plugins() {
  echo "Cloning external plugins..."

  local customPluginthemeDir=$ZSH_CUSTOM/plugins
  local externalPlugins=(
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-syntax-highlighting
  )

  for repo in $externalPlugins; do
    if [ ! -d $customPluginthemeDir/${repo:t} ]; then
      git clone https://github.com/${repo} $customPluginthemeDir/${repo:t}
    fi
  done
}

function init() {
  rsync --include ".zsh*" \
    --include ".zsh/**" \
    --include ".p10k.zsh" \
    --include ".aliases" \
    --include ".gitconfig" \
    --include ".gitignore.txt" \
    --include ".gitmessage.txt" \
    --include ".git_template/" \
    --include ".git_template/**" \
    --include ".vim*" \
    --include ".vim/**" \
    --include ".tmux*" \
    --include ".bin/" \
    --include ".bin/**" \
    --include ".alacritty.yml" \
    --include ".config*" \
    --include ".config/**" \
    --exclude "*" \
    -avh --no-perms . ~
  source ~/.zshrc

  if [ $SHELL != '/bin/zsh' ]; then
    chsh -s $(which zsh) # make zsh your default shell
  fi
}

clone_external_plugins

if [[ $1 == "--force" ]] || [[ $1 == "-f" ]]; then
  init
else
  # -q for yes/no answers
  if read -q '?This may overwrite existing files in your home directory. Are you sure? (y/n)'; then
    echo ""
    init
  fi
fi

unset init
