#!/bin/sh

if [[ ! -f $(which brew) ]]; then
  echo "Oh no! Dotfiles requires Homebrew to be installed. Please visit https://brew.sh for installation instructions. Execute me again when brew is installed."
  exit 1
fi

brew update

function install_casks() {
  brew tap homebrew/cask
  brew tap homebrew/cask-fonts

  devTools=(
    'iterm2'
    'visual-studio-code'
    'insomnia' # API development
    'postman' # API development
    'docker'
    'spotify'
    'github' # get native notifications from github, not emails
    # 'wireshark' # network protocol analyzer
  )
  utilities=(
    '1password'
    'google-chrome'
    'brave-browser'
    'firefox'
    'inkscape' # vector graphics editor
    'vlc'
    'notion' # note taking
    'obsidian' # note taking
    'tunnelblick' # vpn client
    'calibre' # ebook management
    # 'nordvpn'
    'raindropio' # bookmark manager
    'logi-options-plus' # logitech mouse configuration
  )
  social=(
    'telegram'
  )
  fonts=(
    'font-fira-code'
    'font-jetbrains-mono'
  )
  all=(
    "${devTools[@]}"
    "${utilities[@]}"
    "${social[@]}"
    "${fonts[@]}"
  )

  brew install --cask $all
}

function install_gnu_utils() {
  brew install gnu-sed # patches sed to be unix compatible

  # Replaces standard Mac OS X utilities with GNU core utilities List of all commands can be found
  # here: https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands Initially available with
  # 'g' prefix (grm, gmv etc.)
  brew install coreutils

  # Extending directory search and file locating capabilities https://www.gnu.org/software/findutils/
  brew install findutils
}

function install_formulas() {
  devUtils=(
    'git'
    'gh'  #github cli
    'svn' # svn isn't shipped with XCode by default anymore
    'python3'
    'bat' # colorful cat
    'docker-compose'
    'neovim'
    'tmux'
    'asdf' # runtime version manager
  )
  utils=(
    'p7zip' # 7zip archiver
    # Use to convert & minimize video quality like: ffmpeg -i input.mov -vcodec libx265 -crf 28 output.mp4
    'ffmpeg'
    # Improves git diff https://github.com/so-fancy/diff-so-fancy gitconfig should be additionally
    # configured to apply it for every diff.
    'diff-so-fancy'
    'ghostscript' # interpreter for the PostScript language and for PDF
    'imagemagick' # image manipulation
  )

  brew install $devUtils
  brew install $utils

  # Installing yarn without global node dependency
  # https://gist.github.com/AGutierrezR/2c22fdd8686e6e30c56949f5e37e214e
  # brew install yarn --ignore-dependencies

  # fzf is a general-purpose command-line fuzzy finder.
  brew install fzf
  $(brew --prefix)/opt/fzf/install
}

install_formulas
install_gnu_utils
install_casks
